import type { DashboardData } from "./system-vivo-types";

export const initialDashboardData: DashboardData = {
  databaseAvailable: false,
  spaces: [
    {
      id: "parque-ferroviario-colegiales",
      name: "Parque Ferroviario Colegiales",
      neighborhood: "Colegiales",
      commune: 13,
      type: "Parque",
      status: "case-study",
      description: "Caso testigo desarrollado: un parque construido por etapas sobre suelo ferroviario, con fuentes documentales, observación y evaluación en proceso.",
      sourceLabel: "Buenos Aires Data · Espacios verdes",
      sourceUrl: "https://data.buenosaires.gob.ar/dataset/espacios-verdes",
      sourceUpdatedAt: "2026-07-06",
    },
    {
      id: "parque-de-la-estacion",
      name: "Parque de la Estación",
      neighborhood: "Balvanera",
      commune: 3,
      type: "Parque",
      status: "reference",
      description: "Caso de referencia para gestión participativa, recuperación ferroviaria y construcción de programas con la comunidad.",
      sourceLabel: "Catálogo preliminar",
      sourceUrl: "https://buenosaires.gob.ar/",
    },
    {
      id: "parque-saavedra",
      name: "Parque Saavedra",
      neighborhood: "Saavedra",
      commune: 12,
      type: "Parque",
      status: "catalog",
      description: "Registro preliminar. Todavía no cuenta con una investigación completa dentro de Sistema Vivo.",
      sourceLabel: "Catálogo preliminar",
      sourceUrl: "https://data.buenosaires.gob.ar/dataset/espacios-verdes",
    },
  ],
  evidence: [
    {
      id: "ev-etapas",
      spaceId: "parque-ferroviario-colegiales",
      title: "El parque fue construido por etapas",
      detail: "La lectura del proyecto exige comparar antecedentes, obra ejecutada y funcionamiento actual; no puede tratarse como una pieza única y cerrada.",
      dimension: "Historia y proyecto",
      state: "validada",
      method: "Documentación pública",
      limitation: "Falta incorporar la totalidad de los planos conforme a obra.",
      sourceTitle: "Documentación pública del Parque Ferroviario",
    },
    {
      id: "ev-flujos",
      spaceId: "parque-ferroviario-colegiales",
      title: "La permanencia no se distribuye de forma homogénea",
      detail: "Durante cinco recorridos de fin de semana se observó mayor concentración cerca del anfiteatro y menor permanencia en el sector de vagones.",
      dimension: "Usos y flujos",
      state: "contextual",
      method: "Observación de campo · 17 a 19 h",
      limitation: "Un solo día no permite generalizar el comportamiento anual ni semanal.",
      observedAt: "2026-08-30",
    },
    {
      id: "ev-accesibilidad",
      spaceId: "parque-ferroviario-colegiales",
      title: "La accesibilidad no es continua",
      detail: "El recorrido principal es transitable, pero aparecen desniveles, bordes y equipamientos con accesos diferentes entre sí.",
      dimension: "Accesibilidad y cuidados",
      state: "contextual",
      method: "Recorrido acompañado por una persona mayor con bastón",
      limitation: "Debe contrastarse con auditoría técnica y otros perfiles de movilidad.",
      observedAt: "2026-08-30",
    },
  ],
  issues: [
    {
      id: "issue-continuidad",
      spaceId: "parque-ferroviario-colegiales",
      title: "La evidencia no continúa hasta la decisión",
      statement: "Planos, reclamos, voces, observaciones y evaluaciones existen, pero permanecen separados. Así se dificulta reconocer relaciones, responsables y oportunidades comunes.",
      status: "en investigación",
      affectedActors: "Usuarios cotidianos, organizaciones, equipos técnicos y organismos responsables",
      evidenceCount: 3,
    },
  ],
  evaluations: [
    { id: "eval-ante", spaceId: "parque-ferroviario-colegiales", stage: "Ex-ante", period: "2017–2024", coverage: 47, score: null, note: "Cobertura documental vinculada. No equivale al resultado del parque." },
    { id: "eval-post", spaceId: "parque-ferroviario-colegiales", stage: "Ex-post", period: "2024–2026", coverage: 100, score: null, note: "Carga informada como completa; el puntaje permanece bloqueado hasta validar respuestas obligatorias." },
    { id: "eval-expectativa", spaceId: "parque-ferroviario-colegiales", stage: "Expectativa", period: "Próxima intervención", coverage: 0, score: null, note: "Se habilita cuando existe una propuesta medible y permite volver a evaluar después de implementarla." },
  ],
  relations: [],
  stakeholders: [],
  projects: [],
  regulations: [],
  entityLinks: [],
};
