CREATE TABLE `relations` (
	`id` text PRIMARY KEY NOT NULL,
	`source_space_id` text NOT NULL,
	`target_space_id` text NOT NULL,
	`title` text NOT NULL,
	`shared_mechanisms` text NOT NULL,
	`explanation` text NOT NULL,
	`transferable_lesson` text NOT NULL,
	`limitation` text NOT NULL,
	`evidence_state` text DEFAULT 'documentada' NOT NULL
);
--> statement-breakpoint
CREATE INDEX `relations_source_idx` ON `relations` (`source_space_id`);--> statement-breakpoint
CREATE INDEX `relations_target_idx` ON `relations` (`target_space_id`);
--> statement-breakpoint
INSERT OR IGNORE INTO `spaces` (`id`,`name`,`neighborhood`,`commune`,`type`,`status`,`description`,`source_label`,`source_url`,`source_updated_at`,`official_id`,`location`,`area_sqm`,`latitude`,`longitude`) VALUES
('parque-ferroviario-colegiales','Parque Ferroviario Colegiales','Colegiales',13,'Parque','case-study','Caso testigo desarrollado: un parque construido por etapas sobre suelo ferroviario, con fuentes documentales, observación y evaluación en proceso.','Buenos Aires Data · Espacios verdes','https://data.buenosaires.gob.ar/dataset/espacios-verdes','2026-07-06','2231','AV FEDERICO LACROZE, MOLDES, OLAGUER Y FELIU VIRREY, CRAMER',14199.59679262234,-34.57154502215185,-58.45064213145611),
('parque-de-la-estacion','Parque de la Estación','Balvanera',3,'Parque','reference','Caso de referencia para gestión participativa, recuperación ferroviaria y construcción de programas con la comunidad.','Buenos Aires Data · Espacios verdes','https://data.buenosaires.gob.ar/dataset/espacios-verdes','2026-07-06','1842','PERON JUAN DOMINGO - ANCHORENA TOMAS - VÍAS DEL FFCC SARMIENTO - DIAZ VELEZ AV - GALLO',4394.166374326971,-34.60780313710249,-58.41308423782606),
('parque-saavedra','Parque Saavedra','Saavedra',12,'Parque','catalog','Registro preliminar. Todavía no cuenta con una investigación completa dentro de Sistema Vivo.','Buenos Aires Data · Espacios verdes','https://data.buenosaires.gob.ar/dataset/espacios-verdes','2026-07-06','171','GARCIA DEL RIO, AV. - MELIAN, AV. - VILELA - PEREZ, ROQUE - BESARES - CONDE - PINTO - FREIRE, RAMON, CAP. GRAL.',96070.01479020756,-34.55060748312994,-58.48008060772224);
--> statement-breakpoint
UPDATE `spaces` SET `status`='reference', `description`='Caso ferroviario documentado para comparar obra por etapas, eliminación de barreras urbanas y presión de flujos metropolitanos.' WHERE `id`='oficial-2357';
--> statement-breakpoint
UPDATE `spaces` SET `status`='reference', `description`='Caso ferroviario documentado para estudiar cómo un gran desarrollo residencial modifica los usuarios esperados y exige mantenimiento posterior.' WHERE `id`='oficial-1989';
--> statement-breakpoint
UPDATE `spaces` SET `status`='reference', `description`='Caso documentado de recuperación ferroviaria, patrimonio y gestión participativa mediante una Mesa de Trabajo y Consenso.' WHERE `id`='parque-de-la-estacion';
--> statement-breakpoint
INSERT INTO `spaces` (`id`,`name`,`neighborhood`,`commune`,`type`,`status`,`description`,`source_label`,`source_url`,`source_updated_at`,`location`,`latitude`,`longitude`) VALUES
('corredor-donado-holmberg','Corredor Donado–Holmberg','Villa Urquiza',12,'Corredor urbano','reference','Caso sistémico para comparar continuidad peatonal, cruces, responsabilidades público-privadas y transformación de una traza urbana inconclusa.','BA Obras Histórico','https://data.buenosaires.gob.ar/dataset/ba-obras/resource/1cac390f-0713-4d4e-b48a-de812e1c92f8','2026-09-04','Donado y Holmberg, entre Congreso y Carbajal',-34.570533,-58.475614);
--> statement-breakpoint
INSERT INTO `sources` (`id`,`space_id`,`title`,`publisher`,`kind`,`url`,`published_at`,`checked_at`,`reliability`) VALUES
('src-pde-ley','parque-de-la-estacion','Ley 5734 · Parque de la Estación','Legislatura CABA','Normativa','https://boletinoficial.buenosaires.gob.ar/normativaba/norma/346961','2017-01-24','2026-09-04','primaria'),
('src-pde-proyecto','parque-de-la-estacion','Proyecto Parque de la Estación','GCBA','Proyecto','https://buenosaires.gob.ar/gcaba_historico/desarrollourbano/desarrollo/parque-de-la-estacion',NULL,'2026-09-04','primaria'),
('src-pfp-etapa','oficial-2357','Primera etapa del Parque Ferroviario Palermo','GCBA','Proyecto','https://buenosaires.gob.ar/gcaba_historico/noticias/fotogaleria-del-nuevo-parque-ferroviario-de-palermo','2019-11-06','2026-09-04','primaria'),
('src-peba-mantenimiento','oficial-1989','Puesta en valor del Parque Estación Buenos Aires','GCBA','Mantenimiento','https://buenosaires.gob.ar/gcaba_historico/noticias/puesta-en-valor-del-parque-estacion-buenos-aires','2023-03-27','2026-09-04','primaria'),
('src-peba-viviendas','oficial-1989','Desarrollo Urbanístico Estación Buenos Aires','Presidencia de la Nación','Proyecto','https://www.argentina.gob.ar/noticias/procrear-ii-ferraresi-entrego-viviendas-en-ciudad-autonoma-de-buenos-aires','2022-02-07','2026-09-04','primaria'),
('src-dh-proyecto','corredor-donado-holmberg','Barrio Parque Donado Holmberg','GCBA','Proyecto','https://buenosaires.gob.ar/gcaba_historico/noticias/el-barrio-parque-donado-holmberg-es-una-realidad','2015-06-04','2026-09-04','primaria'),
('src-dh-obras','corredor-donado-holmberg','Calle Holmberg: nivelación en cruce','Buenos Aires Data','Obra pública','https://data.buenosaires.gob.ar/dataset/ba-obras/resource/1cac390f-0713-4d4e-b48a-de812e1c92f8',NULL,'2026-09-04','primaria');
--> statement-breakpoint
INSERT INTO `evidence` (`id`,`space_id`,`source_id`,`title`,`detail`,`dimension`,`state`,`method`,`limitation`,`observed_at`) VALUES
('ev-pde-participacion','parque-de-la-estacion','src-pde-ley','La participación tiene una estructura institucional','La Ley 5734 crea una Mesa de Trabajo y Consenso abierta para diseñar y monitorear el Plan de Manejo, con organismos, comunas, personas y organizaciones.','Actores y gobernanza','validada','Lectura normativa','La participación es no vinculante en varias funciones y su existencia legal no demuestra por sí sola la calidad de cada proceso.',NULL),
('ev-pde-patrimonio','parque-de-la-estacion','src-pde-proyecto','El patrimonio ferroviario se integra a nuevos usos','El proyecto recupera el galpón ferroviario y combina espacios culturales, deportivos, de reunión y biblioteca con superficie verde pública.','Historia y proyecto','validada','Documento oficial de proyecto','Describe objetivos y programa; requiere contraste con funcionamiento actual.',NULL),
('ev-pfp-etapas','oficial-2357','src-pfp-etapa','La obra fue planteada por etapas y para reconectar sectores','La primera etapa incorporó 5.000 m², áreas de juego, recorrido aeróbico y estar; el proyecto declaró como objetivo eliminar paredones y barreras entre Palermo Soho y Hollywood.','Historia y proyecto','validada','Documento oficial de obra','Las cifras y beneficios son objetivos institucionales; falta una evaluación independiente posterior.',NULL),
('ev-pfp-flujos','oficial-2357','src-pfp-etapa','El área recibe flujos barriales y metropolitanos','El documento identifica vecinos, trabajadores y grandes flujos de tren, subte, Metrobus y colectivos como población potencialmente beneficiaria.','Usos, flujos y actores','validada','Documento oficial de proyecto','Son poblaciones potenciales, no conteos observados dentro del parque.',NULL),
('ev-peba-cambio','oficial-1989','src-peba-viviendas','El entorno incorporó una nueva población residente','El desarrollo urbanístico Estación Buenos Aires reúne 2.476 departamentos, infraestructura y espacios verdes, modificando la demanda cotidiana del sector.','Usos, flujos y actores','validada','Documento oficial de programa','La cantidad de viviendas no permite inferir por sí sola quién usa el parque ni en qué horarios.',NULL),
('ev-peba-post','oficial-1989','src-peba-mantenimiento','El espacio requirió una intervención posterior','En 2023 se renovaron el piso antigolpes, los juegos y escaladores integradores del parque.','Mantenimiento y post-ocupación','validada','Registro oficial de puesta en valor','El registro confirma la intervención, pero no explica qué evaluación previa motivó cada decisión.',NULL),
('ev-dh-continuidad','corredor-donado-holmberg','src-dh-obras','Los cruces se trataron como parte del sistema','La obra niveló intersecciones del corredor para construir continuidad física y espacial entre pequeñas plazas y tramos lineales.','Accesibilidad y conectividad','validada','Registro oficial de obra','El caso surge de una traza de autopista inconclusa, no de suelo ferroviario.',NULL),
('ev-dh-escalas','corredor-donado-holmberg','src-dh-proyecto','La transformación combinó vivienda, espacio público y escala barrial','El proyecto abarcó 13 manzanas y articuló soluciones habitacionales, recuperación patrimonial, ambiente y espacio público.','Actores y gobernanza','validada','Documento oficial de proyecto','El documento institucional describe resultados favorables y debe complementarse con voces y evaluación independiente.',NULL);
--> statement-breakpoint
INSERT INTO `relations` (`id`,`source_space_id`,`target_space_id`,`title`,`shared_mechanisms`,`explanation`,`transferable_lesson`,`limitation`,`evidence_state`) VALUES
('rel-colegiales-estacion','parque-ferroviario-colegiales','parque-de-la-estacion','Patrimonio ferroviario y gestión compartida','["suelo ferroviario","patrimonio","participación","plan de manejo"]','Ambos recuperan suelo e infraestructura ferroviaria y requieren coordinar proyecto, uso y gestión posterior.','La Mesa de Trabajo y Consenso muestra cómo dar continuidad institucional a las voces y conectar comunidad, comunas y áreas técnicas.','La Ley 5734 crea un dispositivo específico para Parque de la Estación; no puede trasladarse automáticamente sin revisar competencias y voluntad institucional.','documentada'),
('rel-colegiales-palermo','parque-ferroviario-colegiales','oficial-2357','Etapas, barreras y flujos metropolitanos','["obra por etapas","barreras urbanas","movilidad","espacio lineal"]','Los dos parques surgen junto a infraestructuras ferroviarias y se entienden mejor al comparar etapas, conexiones y poblaciones que atraviesan el área.','Permite evaluar cada etapa no sólo por superficie construida, sino por la continuidad lograda entre barrios, accesos y modos de transporte.','Palermo se desarrolla bajo un viaducto y con flujos de otra escala; sus cifras potenciales no equivalen a uso observado.','documentada'),
('rel-colegiales-estacion-ba','parque-ferroviario-colegiales','oficial-1989','Nueva población y evaluación post-ocupación','["suelo ferroviario","nuevos residentes","mantenimiento","evaluación posterior"]','Ambos combinan recuperación ferroviaria con transformaciones urbanas que cambian quiénes pueden usar el espacio y qué mantenimiento requiere.','Relacionar nuevas viviendas, perfiles de usuarios y ajustes posteriores ayuda a anticipar demandas sin confundir población residente con uso real.','La evidencia disponible de Estación Buenos Aires es institucional; aún faltan flujos, entrevistas y evaluación equivalente al caso Colegiales.','documentada con faltantes'),
('rel-colegiales-donado','parque-ferroviario-colegiales','corredor-donado-holmberg','Continuidad, cruces y responsabilidades','["corredor lineal","cruces","fragmentación","gestión multiactor"]','Aunque tienen orígenes diferentes, ambos muestran que una sucesión de piezas verdes sólo funciona como sistema si resuelve cruces, bordes y responsabilidades.','La nivelación de cruces permite tratar la conectividad como una intervención medible y no como un atributo abstracto del proyecto.','Donado–Holmberg proviene de la ex AU3 y no es un parque único; se usa como analogía de mecanismo, no como equivalencia territorial.','documentada');
