INSERT OR IGNORE INTO `sources` (`id`,`space_id`,`title`,`publisher`,`kind`,`url`,`published_at`,`checked_at`,`reliability`) VALUES
('src-ba-verdes','parque-ferroviario-colegiales','Espacios verdes','Buenos Aires Data','Dataset','https://data.buenosaires.gob.ar/dataset/espacios-verdes',NULL,'2026-09-05','primaria'),
('src-dganu-manual','parque-ferroviario-colegiales','Manual de evaluación de espacios públicos con perspectiva de género y diversidad','DGANU · GCBA','Manual','https://buenosaires.gob.ar/gcaba_historico/manual-de-diseno-de-espacios-publicos-con-perspectiva-de-genero-y-diversidad',NULL,'2026-09-05','primaria'),
('src-haene-reservorios','parque-ferroviario-colegiales','Terraplenes y playones ferroviarios son reservorios de biodiversidad urbana','Eduardo Haene y equipo','Paper','https://www.researchgate.net/publication/381796547_Terraplenes_y_playones_ferroviarios_son_reservorios_de_biodiversidad_urbana',NULL,'2026-09-05','académica'),
('src-haene-carteles','parque-ferroviario-colegiales','Carteles de árboles nativos de la Argentina en el Parque Ferroviario Colegiales','Eduardo Haene y equipo','Paper','https://www.researchgate.net/publication/380367282_Carteles_de_arboles_nativos_de_la_Argentina_en_el_Parque_Ferroviario_Colegiales',NULL,'2026-09-05','académica'),
('src-haene-jardineria','parque-ferroviario-colegiales','Buenas prácticas de jardinería para el parche de pastizal pampeano','Eduardo Haene y equipo','Paper','https://www.researchgate.net/publication/387744831_Buenas_practicas_de_jardineria_para_el_parche_de_pastizal_pampeano_en_el_Parque_Ferroviario_Colegiales',NULL,'2026-09-05','académica');
--> statement-breakpoint
INSERT OR IGNORE INTO `evidence` (`id`,`space_id`,`source_id`,`title`,`detail`,`dimension`,`state`,`method`,`limitation`,`observed_at`) VALUES
('ev-etapas','parque-ferroviario-colegiales','src-ba-verdes','El parque debe leerse como una construcción por etapas','Antecedentes, obra ejecutada y funcionamiento actual no forman una única fotografía temporal; deben compararse por sector y período.','Historia, proyectos y etapas','validada','Documentación pública y cronología del caso','Falta vincular la totalidad de los planos conforme a obra.',NULL),
('ev-flujos','parque-ferroviario-colegiales',NULL,'La permanencia no se distribuye de manera homogénea','En cinco recorridos realizados entre las 17 y las 19 h se registró mayor concentración cerca del anfiteatro y menor permanencia en el sector de vagones.','Usos, flujos y tiempos','contextual','Observación de campo · cinco recorridos','Corresponde a un domingo de clima favorable; no representa por sí solo la semana ni el año.','2026-08-30'),
('ev-accesibilidad','parque-ferroviario-colegiales',NULL,'La accesibilidad del recorrido no garantiza la del sistema completo','El sendero principal resultó transitable, pero aparecieron desniveles, bordes y diferencias de acceso entre equipamientos y glorietas.','Accesos y conectividad','contextual','Recorrido acompañado por una persona de 90 años con bastón','Debe contrastarse con una auditoría técnica y con otros perfiles de movilidad.','2026-08-30'),
('ev-cesped','parque-ferroviario-colegiales',NULL,'La demanda de permanencia presiona sectores de césped habilitados','Se observaron mantas, juegos, perros y permanencias concentradas en el césped disponible, mientras un sector central permanecía cercado.','Usos, flujos y tiempos','contextual','Observación y registro fotográfico','No se verificó el motivo del cercado ni el plan de recuperación del césped.','2026-08-30'),
('ev-canil','parque-ferroviario-colegiales',NULL,'El canil tiene baja visibilidad desde los recorridos principales','El equipamiento fue difícil de identificar durante visitas previas y presentó señales de mantenimiento insuficiente en el relevamiento.','Equipamiento y mantenimiento','contextual','Observación y registro fotográfico','Falta una inspección técnica, frecuencia de mantenimiento y encuesta específica a personas con perros.','2026-08-30'),
('ev-luces','parque-ferroviario-colegiales',NULL,'El encendido de iluminación pudo registrarse con hora exacta','Durante el relevamiento las luminarias se encendieron a las 18:34.','Equipamiento y mantenimiento','contextual','Registro horario de campo','Es un único registro; debe repetirse en otras fechas y condiciones de luz.','2026-08-30'),
('ev-biodiversidad','parque-ferroviario-colegiales','src-haene-reservorios','La infraestructura ferroviaria también puede sostener biodiversidad urbana','La bibliografía especializada reconoce terraplenes y playones ferroviarios como ambientes con valor para la biodiversidad urbana.','Ambiente, clima y biodiversidad','validada','Revisión de paper especializado','El valor general de estos ambientes no reemplaza un inventario actualizado del parque.',NULL),
('ev-nativas','parque-ferroviario-colegiales','src-haene-carteles','El parque incorpora comunicación sobre árboles nativos','Existe un trabajo específico sobre los carteles de árboles nativos instalados en el Parque Ferroviario Colegiales.','Ambiente, clima y biodiversidad','validada','Revisión de publicación especializada','La presencia de cartelería no permite evaluar por sí sola estado, sombra ni supervivencia de ejemplares.',NULL),
('ev-pastizal','parque-ferroviario-colegiales','src-haene-jardineria','El parche de pastizal necesita prácticas de manejo específicas','La publicación propone buenas prácticas de jardinería para conservar el parche de pastizal pampeano del parque.','Ambiente, clima y biodiversidad','validada','Revisión de publicación especializada','Debe verificarse qué prácticas están vigentes y quién realiza el mantenimiento.',NULL),
('ev-dganu','parque-ferroviario-colegiales','src-dganu-manual','La evaluación separa antecedentes, funcionamiento y experiencia','El Manual DGANU permite ordenar preguntas ex-ante y ex-post por dimensiones; Sistema Vivo conserva faltantes y fuentes antes de emitir resultados.','Evaluación DGANU','validada','Aplicación metodológica del manual','El manual orienta la evaluación, pero no reemplaza los datos de campo ni la decisión situada.',NULL),
('ev-actores','parque-ferroviario-colegiales',NULL,'En el parque conviven usuarios cotidianos y responsables de distintas jurisdicciones','Personas de paso, familias, personas mayores, personas con discapacidad, deportistas, personas con mascotas, organizaciones, GCBA y organismos ferroviarios intervienen de maneras diferentes.','Actores y responsabilidades','contextual','Mapa de actores del proceso de investigación','Falta validar responsabilidades vigentes y entrevistar a responsables del proyecto.',NULL),
('ev-voces','parque-ferroviario-colegiales',NULL,'Las voces sólo son evidencia cuando conservan contexto','Las entrevistas y conversaciones se registran con perfil, momento, actividad y limitación; no se convierten automáticamente en porcentajes.','Voces y participación','contextual','Entrevistas y conversaciones exploratorias','La muestra todavía no es representativa de todos los perfiles y horarios.',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO `issues` (`id`,`space_id`,`title`,`statement`,`status`,`affected_actors`,`evidence_count`) VALUES
('issue-continuidad','parque-ferroviario-colegiales','La evidencia no continúa hasta la decisión','Planos, reclamos, voces, observaciones y evaluaciones existen, pero permanecen separados. Esto dificulta reconocer relaciones, responsables y oportunidades comunes.','en investigación','Usuarios cotidianos, organizaciones, equipos técnicos y organismos responsables',12),
('issue-ocupacion','parque-ferroviario-colegiales','La ocupación del parque cambia abruptamente entre sectores','El relevamiento muestra una concentración de permanencias cerca del anfiteatro y una caída en el sector de vagones; falta repetir el conteo para explicar qué condiciones producen esa diferencia.','hipótesis a contrastar','Personas que permanecen, atraviesan o evitan determinados sectores',2),
('issue-acceso','parque-ferroviario-colegiales','La accesibilidad aparece como una cadena discontinua','Un recorrido principal transitable convive con bordes, desniveles y equipamientos con accesos desiguales, por lo que la experiencia completa puede interrumpirse.','hipótesis a contrastar','Personas mayores, con discapacidad, infancias y quienes realizan tareas de cuidado',1);
--> statement-breakpoint
INSERT OR IGNORE INTO `evaluations` (`id`,`space_id`,`stage`,`period`,`coverage`,`score`,`note`) VALUES
('eval-ante','parque-ferroviario-colegiales','Ex-ante','2017–2024',47,NULL,'Cobertura documental vinculada. No equivale al resultado del parque.'),
('eval-post','parque-ferroviario-colegiales','Ex-post','2024–2026',100,NULL,'La carga está completa; el puntaje permanece bloqueado hasta validar las respuestas obligatorias.'),
('eval-expectativa','parque-ferroviario-colegiales','Expectativa','Próxima intervención',0,NULL,'Se habilita cuando existe una propuesta medible y permite volver a evaluar después de implementarla.');
